defaults: &defaults
  TIMEZONE: 'Paris'

  # Configuration variables for Redis.
  REDIS_URL:      redis://localhost:6379
  REDIS_PASSWORD: ~ # By default no password is sent to Redis server. Change this if you want to connect using password.

  # admin role account
  ADMIN: 'admin@cactoken.net'

<<<<<<< HEAD
  # site host
  URL_HOST: cactoken.net:3000
  URL_SCHEME: http
=======
  #  database.yml variables
  #  RDS_HOSTNAME: dietbitcoinico-org.c0vfzk4vecgn.us-east-1.rds.amazonaws.com
  RDS_HOSTNAME: 
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce

  # session expire time (seconds)
  SESSION_EXPIRE: '60'

  #  database.yml variables
  RDS_HOSTNAME: localhost

  # Configuration variables for mailer (production only).
  #
  # The variables below are the minimal set of configuration required for mailer to work.
  #
  # More variables are available at:
  # – https://github.com/mikel/mail
  # – http://api.rubyonrails.org/v4.2/classes/ActionMailer/Base.html
  # – config/environments/production.rb at config.action_mailer.smtp_settings
  #
<<<<<<< HEAD
  SMTP_ADDRESS:             
  SMTP_PORT:                
  SMTP_USERNAME:            
  SMTP_PASSWORD:            
  SMTP_AUTHENTICATION_TYPE: 
  SMTP_DOMAIN:  ''

  # email accounts
  SUPPORT_MAIL:
  SYSTEM_MAIL_FROM:
  SYSTEM_MAIL_TO:
  OPERATE_MAIL_TO:
=======
  SMTP_ADDRESS: 
  SMTP_PORT:    
  SMTP_USERNAME: 
  SMTP_PASSWORD: 
  SMTP_AUTHENTICATION_TYPE: # Can be plain, login or cram_md5.

  S3_ACCESS_KEY: 
  S3_SECRET_KEY: 
  S3_BUCKET_NAME:


  # email accounts
  SUPPORT_MAIL: 
  SYSTEM_MAIL_FROM:
  SYSTEM_MAIL_TO: 
  OPERATE_MAIL_TO: 
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce

  # WebSocket Streaming API settings
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: '8080'

  # Uncomment following lines to enable secure WebSocket (wss)
  # WEBSOCKET_SSL_KEY: 'your_server.key'
  # WEBSOCKET_SSL_CERT: 'your_server.crt'

<<<<<<< HEAD
  # pusher settings
  PUSHER_APP: '472220'
  PUSHER_KEY: 8ac9bbc74f1dd43252c7
  PUSHER_SECRET: 3a508bed5e38045c1b48
=======
  RABBITMQ_HOST: 
  RABBITMQ_PORT: 
  RABBITMQ_USER: 
  RABBITMQ_PASSWORD:

  PUSHER_APP: 
  PUSHER_KEY: 
  PUSHER_SECRET:
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: '80'
  PUSHER_WS_PORT: '80'
  PUSHER_WSS_PORT: '443'
  PUSHER_ENCRYPTED: 'on'

<<<<<<< HEAD
  # twilio setting (https://github.com/twilio/twilio-ruby)
  TWILIO_NUMBER: 
  TWILIO_SID: 
  TWILIO_TOKEN: 
=======
  TWILLIO_REGION: 'HK'
  TWILIO_NUMBER:
  TWILIO_SID: 
  TWILIO_TOKEN:
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce

  RECAPTCA_SITE_KEY: 
  RECAPTCA_SECRET_KEY:

  # Configuration variables for sign in with Google.
  # See https://github.com/zquestz/omniauth-google-oauth2
  GOOGLE_OAUTH2_SIGN_IN:      ~ # Set to "on" to enable.
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  GOOGLE_OAUTH2_REDIRECT_URL: ~ # Specify URL address to which user will be redirected after successful sign in.

  # Configuration variables for sign in with Auth0.
  # See https://github.com/auth0/omniauth-auth0
  AUTH0_OAUTH2_SIGN_IN:       ~ # Set to "on" to enable.
  AUTH0_OAUTH2_DOMAIN:
  AUTH0_OAUTH2_CLIENT_ID:
  AUTH0_OAUTH2_CLIENT_SECRET:
  AUTH0_OAUTH2_REDIRECT_URL:  ~ # Specify URL address to which user will be redirected after successful sign in.

  # Configuration variables for API CORS.
  #
  # Set list of allowed origins using the variable below.
  # By default it allows access to API from all origins.
  # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
  API_CORS_ORIGINS: '*'

  # Configuration variables for Sentry.
  SENTRY_ENV:          production # Specify environments separated by comma for which Sentry should be initialized.
  SENTRY_DSN_BACKEND:  ~          # Specify Sentry DSN used for Rails application.
  SENTRY_DSN_FRONTEND: ~          # Specify Sentry DSN used for JavaScript application.

  # Configuration variables for appearance.
  LOGO_URL:                       ~
  HEADER_BACKGROUND_COLOR:        ~
  HEADER_BORDER_COLOR:            ~
  HEADER_LINK_COLOR:              ~
  HEADER_LINK_HOVER_COLOR:        ~
  HEADER_RUBRIC_ACTIVE_COLOR:     ~
  HEADER_RUBRIC_BACKGROUND_COLOR: ~
  MAIL_HEADER_BACKGROUND_COLOR:   ~

  # Configuration variables for webhooks.
  WEBHOOKS_SECURE_URL_COMPONENT: ~ # Optional. Set value if you want to secure URL to webhooks.
  # Example:
  #   When WEBHOOKS_SECURE_URL_COMPONENT is set to "B6p2csgf2h" the URL to webhooks becomes /webhooks/B6p2csgf2h/btc/hook.
  #   The default URL is /webhooks/btc/hook.

development:
  <<: *defaults
  # Development configuration variables for sign in with Google.
<<<<<<< HEAD
  GOOGLE_OAUTH2_SIGN_IN:      
  GOOGLE_CLIENT_ID:           
  GOOGLE_CLIENT_SECRET:       

  # Development configuration variables for sign in with Auth0.
  AUTH0_OAUTH2_SIGN_IN:       
  AUTH0_OAUTH2_DOMAIN:        
  AUTH0_OAUTH2_CLIENT_ID:     
  AUTH0_OAUTH2_CLIENT_SECRET: 

  RAILS_ENV: 'development'
  OS_DATABASE_PASSWORD: 'root'
  OS_DATABASE_USER: '01722gausia'
  OS_DATABASE_HOST: 'localhost'

=======
  GOOGLE_OAUTH2_SIGN_IN:      on
  GOOGLE_CLIENT_ID:    
  GOOGLE_CLIENT_SECRET: 

  # Development configuration variables for sign in with Auth0.
  AUTH0_OAUTH2_SIGN_IN:       on
  AUTH0_OAUTH2_DOMAIN:  
  AUTH0_OAUTH2_CLIENT_ID:
  AUTH0_OAUTH2_CLIENT_SECRET: 

  SECRET_KEY_BASE: 
  JWT_SHARED_SECRET_KEY: 
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce

test:
  <<: *defaults

stage:
  <<: *defaults
  RDS_DB_NAME: 'cactoken'
  RDS_USERNAME: 'user'
  RDS_PASSWORD: 'C@ctok20'
  POOL: 10

<<<<<<< HEAD
  # site host
  URL_HOST: cactoken.net
  URL_SCHEME: http

  RECAPTCA_SITE_KEY: 
  RECAPTCA_SECRET_KEY: 

production:
  <<: *defaults
  # production configuration variables for sign in with Google.
  GOOGLE_OAUTH2_SIGN_IN:    
  GOOGLE_CLIENT_ID:          
  GOOGLE_CLIENT_SECRET:      
  # production configuration variables for sign in with Facebook.
  OMNIAUTH_FACEBOOK_SIGN_IN: 
  FACEBOOK_CLIENT_ID: 
  FACEBOOK_CLIENT_SECRET: 

  RAILS_ENV: 'production'
  OS_DATABASE_PASSWORD: '01722gausia'
  OS_DATABASE_USER: 'root'
  OS_DATABASE_HOST: 'localhost'  
  SECRET_KEY_BASE: ''
  # database yml setting variables
#  RDS_DB_NAME: 'ecb01'
#  RDS_USERNAME: 'ecb01'
#  RDS_PASSWORD: 'loGrbMjqhpITki4Z'
#  POOL: 10

  # site host
  URL_HOST: 57.230.37.177:3000
  URL_SCHEME: http
=======
production:
  <<: *defaults
  RDS_DB_NAME:
  RDS_USERNAME:
  RDS_PASSWORD:
  POOL: 50
  # site host
  URL_HOST: cactoken.net
  URL_SCHEME: https

  # Secret Key
  SECRET_KEY_BASE: 
  JWT_SHARED_SECRET_KEY:
  
  RECAPTCA_SITE_KEY: 
  RECAPTCA_SECRET_KEY:

  REDIS_URL: redis://cactoken.net:6379
  RDS_HOSTNAME: cactoken.net

  # admin role account
  ADMIN: 'dev.cccubes@cactoken.net' # mkK&w9RN

  AIRDROP_CURRENCY: 
  AIRDROP_USER: 

  # Stage configuration variables for sign in with Google. - need to confirm - is it working
  GOOGLE_OAUTH2_SIGN_IN:      on
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 

  # Stage configuration variables for sign in with facebook. - need to confirm - is it working
  OMNIAUTH_FACEBOOK_SIGN_IN:        on
  FACEBOOK_CLIENT_ID	: 
  FACEBOOK_CLIENT_SECRET:

  RABBITMQ_HOST: 
  RABBITMQ_USER: 
  RABBITMQ_PASSWORD: 

  # pusher settings
  PUSHER_APP: 
  PUSHER_KEY: 
  PUSHER_SECRET:
<<<<<<< HEAD

  S3_ACCESS_KEY: 
  S3_SECRET_KEY: 
  S3_BUCKET_NAME: 
  S3_REGION: 

=======

  S3_ACCESS_KEY: 
  S3_SECRET_KEY: 
  S3_BUCKET_NAME: 
  S3_REGION: 
>>>>>>> e1743e9c8b3513ab3f4dbf2ac14a18188d9a7a7e


  SUPPORT_MAIL:
  SYSTEM_MAIL_FROM:
  SYSTEM_MAIL_TO: 
  OPERATE_MAIL_TO:

<<<<<<< HEAD
=======
  SUPPORT_MAIL:
  SYSTEM_MAIL_FROM:
  SYSTEM_MAIL_TO: 
  OPERATE_MAIL_TO:
>>>>>>> e1743e9c8b3513ab3f4dbf2ac14a18188d9a7a7e
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce
