- id: 0
  code: ab
  currency: inr
  deposit: true
  withdraw: true

- id: 1
  code: boi
  currency: inr
  deposit: true
  withdraw: true

- id: 2
  code: cb
  currency: inr
  deposit: true
  withdraw: true

- id: 3
  code: cboi
  currency: inr
  deposit: true
  withdraw: true

- id: 4
  code: fb
  currency: inr
  deposit: true
  withdraw: true

- id: 5
  code: icici
  currency: inr
  deposit: true
  withdraw: true

- id: 6
  code: idbi
  currency: inr
  deposit: true
  withdraw: true

- id: 7
  code: iib
  currency: inr
  deposit: true
  withdraw: true

- id: 8
  code: kb
  currency: inr
  deposit: true
  withdraw: true

- id: 9
  code: psb
  currency: inr
  deposit: true
  withdraw: true

- id: 10
  code: sbi
  currency: inr
  deposit: true
  withdraw: true

- id: 11
  code: sb
  currency: inr
  deposit: true
  withdraw: true

- id: 12
  code: ubi
  currency: inr
  deposit: true
  withdraw: true

- id: 13
  code: yb
  currency: inr
  deposit: true
  withdraw: true

- id: 14
  code: uco
  currency: inr
  deposit: true
  withdraw: true

- id: 15
  code: boc
  currency: inr
  deposit: true
  withdraw: true

- id: 16
  code: wf
  currency: inr
  deposit: true
  withdraw: true

- id: 17
  code: cg
  currency: inr
  deposit: true
  withdraw: true