default: &default
  adapter: mysql2
  encoding: utf8
  colation: utf8_general_ci
  pool: 5
  host: 127.0.0.1
  username: root
<<<<<<< HEAD
  password: 01722gausia
=======
  password: 
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce


development:
  <<: *default
  database: coinchel_dev
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock
  #socket : /var/lib/mysql/mysql.sock
test:
  <<: *default
  database: coinchel_test
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock
  #socket : /var/lib/mysql/mysql.sock

stage:
  <<: *default
  pool: <%= ENV['POOL']%>
  database: <%= ENV['RDS_DB_NAME']%>
  host: <%= ENV['RDS_HOSTNAME']%>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  reconnect: true

# production:
#  <<: *default
#  pool: <%= ENV['POOL']%>
#  database: <%= ENV['RDS_DB_NAME']%>
#  host: <%= ENV['RDS_HOSTNAME']%>
#  username: <%= ENV['RDS_USERNAME'] %>
#  password: <%= ENV['RDS_PASSWORD'] %>
#  reconnect: true

production:
  <<: *default
<<<<<<< HEAD
  pool: 5
  adapter: mysql2
  database: cactoken
  host: 127.0.0.1
  username: user
  password: C@ctok20
  encoding: unicode
  reconnect: true

=======
  pool: <%= ENV['POOL']%>
  database: <%= ENV['RDS_DB_NAME']%>
  host: <%= ENV['RDS_HOSTNAME']%>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  reconnect: true
>>>>>>> 1d584bc086a175960f3d607684059dfe797e0bce
